#!/bin/bash

all="fc_base fc_1 fc_2 fc_3 fc_4 fc_5 fc_6 fc_7 conv_base conv_1 conv_2 conv_3 conv_4"

# if arguments are given, just run the arguments
if [ $# -gt 0 ]; then
	all=$@
fi
for net in $all;
do
	echo Evaluating network ${net}...
	for spec in `ls preliminary_evaluation_test_cases/${net}`
	do	
		echo Evaluating spec ${spec}...
		python code/verifier.py --net ${net} --spec preliminary_evaluation_test_cases/${net}/${spec}
	done
done
